### ISSUE TITLE
Testsuite fails with quite many errors

### ISSUE THREAD

**Issue by nijel** [openSUSE/osc2#8]
When running the testsuite, I get 201 failures. Most of them seem to be related to some problem with xpath, for example:

```
ERROR: test_project1 (test.wc.test_convert.TestConvert)
test project convert
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nijel/suse/osc2/test/wc/test_convert.py", line 81, in test_project1
    convert_project(path)
  File "/home/nijel/suse/osc2/osc2/wc/convert.py", line 106, in convert_project
    apiurl=apiurl, ext_storedir=storedir)
  File "/home/nijel/suse/osc2/osc2/wc/convert.py", line 65, in convert_package
    files.set(filename, ' ')
  File "/home/nijel/suse/osc2/osc2/wc/util.py", line 239, in set
    entry = self.find(name)
  File "/home/nijel/suse/osc2/osc2/wc/util.py", line 236, in find
    return self._xml.find(xp.tostring())
  File "lxml.etree.pyx", line 1459, in lxml.etree._Element.find (src/lxml/lxml.etree.c:49994)
  File "/usr/lib/python2.7/dist-packages/lxml/_elementpath.py", line 281, in find
    it = iterfind(elem, path, namespaces)
  File "/usr/lib/python2.7/dist-packages/lxml/_elementpath.py", line 271, in iterfind
    selector = _build_path_iterator(path, namespaces)
  File "/usr/lib/python2.7/dist-packages/lxml/_elementpath.py", line 241, in _build_path_iterator
    raise SyntaxError("cannot use absolute path on element")
SyntaxError: cannot use absolute path on element
```

**Comment by marcus-h** [comment]
I fixed it some time ago.
